### ISSUE TITLE
(admin,load,start) parameters for start-up script (sfn) need to be documented.

### ISSUE THREAD

**Issue by sddbrown** [PaloAltoNetworks/SafeNetworking#72]
Documentation does not reference the parameters for sfn script:
./sfn > log/console-$(date +%Y-%m-%d_%H:%M).log 2>&1 &

Using kill process in lieu of sfn <stop>.

**Comment by earcuri** [comment]
This has been superseded by the instructions using tmux.  To start, just type startsfn at the cmd prompt.  If SFN is not running, it will create a tmux session, start SFN within it and drop the admin into the session.  If it already is running, then it just drops the admin into the tmux session.  To kill SFN, exit from the tmux session.  To logout, but not exit SFN, use the Ctrl-b, d command and then exit from the system.
